import os
import requests
from openai import OpenAI
from dotenv import load_dotenv
from bs4 import BeautifulSoup
from app.ai.prompts import get_website_analysis_prompt

# Load environment variables
load_dotenv()

class WebsiteAnalyzer:
    """
    A class for scraping and analyzing website content to generate AI insights.
    """

    def __init__(self):
        self.openai_api_key = os.getenv("OPENAI_API_KEY")
        self.client = OpenAI() if self.openai_api_key else None

    def scrape_website(self, url):
        """
        Scrapes the website to extract textual content for analysis.

        Args:
            url (str): The website URL to scrape.

        Returns:
            str: Extracted text content (limited to 5000 characters).
        """
        try:
            headers = {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
            }

            # Make the request with custom headers
            response = requests.get(url, headers=headers, timeout=10)

            # Retry logic for 403 errors
            if response.status_code == 403:
                print(f"Access forbidden for {url}. Retrying...")
                response = requests.get(url, headers=headers, timeout=10)

            response.raise_for_status()  # Raise HTTPError for bad responses

            # Parse HTML content
            soup = BeautifulSoup(response.text, "html.parser")
            paragraphs = soup.find_all("p")
            content = " ".join([para.get_text(strip=True) for para in paragraphs])
            return content[:3000]  # Limit to avoid overwhelming the AI model

        except requests.exceptions.RequestException as e:
            print(f"Error scraping website: {e}")
            return None

    def analyze_website_content(self, content, language):
        """
        Analyzes website content using OpenAI to identify AI solution opportunities.

        Args:
            content (str): The scraped website content.
            language (str): The language of the content (e.g., 'EN' or 'NL').

        Returns:
            str: Insights generated by OpenAI.
        """
        if not self.client:
            print("OpenAI client not initialized. Check your API key.")
            return None

        try:
            analysis_prompt, sys_message = get_website_analysis_prompt(content, language)
            completion = self.client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": sys_message},
                    {"role": "user", "content": analysis_prompt}
                ]
            )
            insights = completion.choices[0].message.content
            return insights

        except Exception as e:
            print(f"Error analyzing website content: {e}")
            return None