
# Full LinkedIn cookies extracted from the browser
linkedin_cookies = [
    {
        "domain": ".linkedin.com",
        "expirationDate": 1753456925,
        "hostOnly": False,
        "httpOnly": False,
        "name": "mbox",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "PC#bd13c4991f9e4243bfd694aa35e022f1.37_0#1753456925|session#7328018511ce4083b22fcd1bca29349d#1737906785"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1740325028.546234,
        "hostOnly": False,
        "httpOnly": False,
        "name": "lms_ads",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "AQG6Q1orNRKk5AAAAZSY9bq3uAx83mNN8dFWkpKu29IpclqgXnBz45x4dhyf0FdmQiZAsUzfCADIEFXm8hNyE2SwLnYJ4z6P"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1769525775.957877,
        "hostOnly": False,
        "httpOnly": False,
        "name": "bcookie",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "\"v=2&2e78fb95-571a-4795-89b5-7c33e0be2d77\""
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1737991701.300717,
        "hostOnly": False,
        "httpOnly": True,
        "name": "__cf_bm",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "qLqEXi05xkt4Rcd_r4ufFTry2lneR6Mo8eY0u_sT8jA-1737989901-1.0.1.1-mTCl8XlajFuxnKJH6R3CLKnJMr4n1Jpibsw6AA3Raibnrmj1kxwQ9YU4WsgtrJwjAAnamXgl4jWxLTou3CXRkQ"
    },
    {
        "domain": "www.linkedin.com",
        "expirationDate": 1769361269,
        "hostOnly": True,
        "httpOnly": False,
        "name": "li_alerts",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "e30="
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1740325028.546296,
        "hostOnly": False,
        "httpOnly": False,
        "name": "lms_analytics",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "AQG6Q1orNRKk5AAAAZSY9bq3uAx83mNN8dFWkpKu29IpclqgXnBz45x4dhyf0FdmQiZAsUzfCADIEFXm8hNyE2SwLnYJ4z6P"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": False,
        "httpOnly": True,
        "name": "fptctx2",
        "path": "/",
        "sameSite": None,
        "secure": True,
        "session": True,
        "storeId": None,
        "value": "taBcrIH61PuCVH7eNCyH0MJojnuUODHcZ6x9WoxhgCm%252b1mM5xbKluPeEI1HMlh7yTzGSYaOcoawF2P1xQOudRZb47t8L%252f9f70IzXouGea0qM2T3g4EKK%252fPeDBo5mwXZ%252brtBQZw%252b5wgnhQMsPFbUSxdM60WgkA9RV7%252bsn2yO7oEVbTn19barFOaUZ2zD2Ryq%252fR03UunMd5P9dIGMpB7FE7fh%252fYiDsS%252buZndC5N%252fDKO36%252fyrZX9JB47NHxT0ysHg3bJyydE9RnXuizYKRqEEhwsKouyVe9iYiyrD5e4Lof3eZiMb0ZqylG05nnGoZO%252bbu5yMdP8OX4kxJ6nuxDgQh0BAeAvULzBn7Tt6eFddsyqvc%253d"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1769361278.489195,
        "hostOnly": False,
        "httpOnly": True,
        "name": "li_at",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "AQEDARniSMIATxYSAAABlJ51WdYAAAGUwoHd1k4Ai0n4qR9IKC9SF1nB4yKNsmJOBPoeTGWPLKLXfMlUzqBQoW2Mk8OFbWFJ1Jy6WSmZ2hNhP9lDAIe42pRkaUMy86PMtY9cF7FMp-y0FZpNE9wFG62A"
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": False,
        "httpOnly": False,
        "name": "lang",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": True,
        "storeId": None,
        "value": "\"v=2&lang=nl-nl\""
    },
    {
        "domain": ".linkedin.com",
        "hostOnly": False,
        "httpOnly": False,
        "name": "at_check",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": True,
        "storeId": None,
        "value": "True"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1738070422.778761,
        "hostOnly": False,
        "httpOnly": False,
        "name": "lidc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "\"b=TB62:s=T:r=T:a=T:p=T:g=8270:u=690:x=1:i=1737989774:t=1738070422:v=2:sig=AQGLT0jHFIqOGUflUOqWnnKA885M4rJ0\""
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1740325028.02218,
        "hostOnly": False,
        "httpOnly": False,
        "name": "AnalyticsSyncHistory",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "AQKijai2nkw4sAAAAZSY9bin-25QLbTPXobnqZaeyd2YJ83u814TtGjff7qLbyOMvF0APEoJM_VUH1nSU6viiw"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1769515483.715519,
        "hostOnly": False,
        "httpOnly": True,
        "name": "bscookie",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "\"v=1&202303151216489359c7c5-896a-4644-8b49-a7b116249872AQFeR2FnPpYYFS5gGbIvg_mGLAVUDMj5\""
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1738403198.352887,
        "hostOnly": False,
        "httpOnly": True,
        "name": "dfpfpt",
        "path": "/",
        "sameSite": "lax",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "4cab0a006ba3438b80059a084bdcbbbe"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1745601278.489336,
        "hostOnly": False,
        "httpOnly": False,
        "name": "JSESSIONID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "\"ajax:3848801668161044514\""
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1739178854.010828,
        "hostOnly": False,
        "httpOnly": False,
        "name": "li_gc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "MTswOzE3MjM2MjY4NTM7MjswMjFgbBqB5kFV51TaKICHoNMJuQD9m+BNfGX/EFDqdWlu4w=="
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1753541714.712194,
        "hostOnly": False,
        "httpOnly": False,
        "name": "li_mc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "MTsyMTsxNzM3OTg5NzE0OzI7MDIxmHfZTtP9MngkH4JitIZDphYDi6rnuqzwIeQklI3a+7k="
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1769361278.488867,
        "hostOnly": False,
        "httpOnly": True,
        "name": "li_rm",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "AQH5Sy_JunFs4gAAAY_K1aUsSB5XCWxRaZ8J58uHfjASnJeLKvdP2FF1rQUumtG5MsJk_Ie-M2uGvocjN1EviJnhN7uI-BGpNiesYe_UsAgJLVfsPmELfOig"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1745765774.957753,
        "hostOnly": False,
        "httpOnly": False,
        "name": "li_sugr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "2029f583-6202-4c7f-8051-6cc1359420d4"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1753537633,
        "hostOnly": False,
        "httpOnly": False,
        "name": "li_theme",
        "path": "/",
        "sameSite": None,
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "light"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1753537633,
        "hostOnly": False,
        "httpOnly": False,
        "name": "li_theme_set",
        "path": "/",
        "sameSite": None,
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "app"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1745601278.489294,
        "hostOnly": False,
        "httpOnly": False,
        "name": "liap",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "True"
    },
    {
        "domain": ".www.linkedin.com",
        "expirationDate": 1739198833,
        "hostOnly": False,
        "httpOnly": False,
        "name": "timezone",
        "path": "/",
        "sameSite": None,
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "Europe/Amsterdam"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1740581234,
        "hostOnly": False,
        "httpOnly": False,
        "name": "UserMatchHistory",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "AQJTSSFNx7fHMAAAAZSoOx5A47zNf_o_sv5yBXYN349j2n_W06oLRRYBuoevKr3jEdsqSzUBtTiZcS_pABNHrVzFeyb4CH5TL9WmrorCLYfEZ7-d4c3JJPkfYluTEXCxdJU73LX9W0fhGalt8hq0RPuofyaCAicjqivhAVaEWlao3_N7NnO4SHJ5xYxf7lD7Ef5XievjFM9yYB1VI3hrNR5fFJ_L0_rS8RUhX2ixzBkbRg1iATqsqFJh4CqGjOuI19TxNYhyrZX0Toqs6A9qvNpXUw1V4rrdNZOBFQq6st7LG2R0NZ-S7Ky0bskeFdrGvsfAl8i6uuzchL0"
    },
    {
        "domain": ".linkedin.com",
        "expirationDate": 1772374887.908887,
        "hostOnly": False,
        "httpOnly": False,
        "name": "visit",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": None,
        "value": "v=1&M"
    }
]